const QUESTIONS = [
  {
    //1
    question: '我通常喜欢和哪些性格的人谈话',
    answer1: '令人愉快&节奏快的人',
    answer1Total: 'I',
    answer2: '知识丰富&逻辑性强',
    answer2Total: 'C',
    answer3: '友好的&真诚的',
    answer3Total: 'S',
    answer4: '聪明&有效率的',
    answer4Total: 'D',
  },

  {
    //2
    question: '最能唤起我的动力的因素是',
    answer1: '挑战&权力',
    answer1Total: 'D',
    answer2: '赢得声望&奖品',
    answer2Total: 'I',
    answer3: '安全&快乐的家庭生活',
    answer3Total: 'S',
    answer4: '完美&专注个人的目标',
    answer4Total: 'C',
  },
  {
    //3
    question: '我通常采用哪种方式试图说服别人',
    answer1: '逻辑性&事实',
    answer1Total: 'C',
    answer2: '热情&说服',
    answer2Total: 'I',
    answer3: '强制&直接',
    answer3Total: 'D',
    answer4: '诚实&对他人的需求很敏感',
    answer4Total: 'S',
  },
  {
    question: '在我同意执行行动之前,我所考虑的是',
    answer1: '所投入的时间、金钱、精力和我个人的利益有多少回报',
    answer1Total: 'D',
    answer2: '是否会涉及一些不可预知的变化,从而 影响我现在的职位',
    answer2Total: 'S',
    answer3: '是否有足够的资料和数据,预示成功的可能性',
    answer3Total: 'C',
    answer4: '是否我会涉及一些新的,令人激动的项目',
    answer4Total: 'I',
  },
  {
    //5
    question: '当人们第一次见到我的时候,可能会认为我',
    answer1: '冲动&健谈',
    answer1Total: 'I',
    answer2: '谨慎&有所保留',
    answer2Total: 'C',
    answer3: '谦虚&保守',
    answer3Total: 'S',
    answer4: '野心勃勃&直接',
    answer4Total: 'D',
  },

  {
    question: '在做一个重要的决定的时候,我会',
    answer1: '力求稳妥,尽可能多收集资料',
    answer1Total: 'C',
    answer2: '快速行动,相信我的直觉和本能',
    answer2Total: 'I',
    answer3: '确保采用自己的方式进行,哪怕可能会有很大的风险',
    answer3Total: 'D',
    answer4: '行动较慢但彻底,尽可能争取他人的支持',
    answer4Total: 'S',
  },

  {
    question: '当给人指导的时候,我会:',
    answer1: '采用大量的身体语言并做最大的努力让其他人参与',
    answer1Total: 'I',
    answer2: '直接进入要点,但有时太简单,或不耐心导致信息传达不完整',
    answer2Total: 'D',
    answer3:
      '准备充分,耐心,善解人意,但有时不清楚哪些信息是最重要的,哪些可以忽略',
    answer3Total: 'S',
    answer4: '准确,有条理,精确但有时因为过多的纠细节使事物更复杂',
    answer4Total: 'C',
  },
  {
    question: '我知道我做了一项很好的工作,当:',
    answer1: '财政结果显示',
    answer1Total: 'C',
    answer2: '我被赋予更多的责任和更困难的任务',
    answer2Total: 'D',
    answer3: '我收到来自于老板或同事的表扬,或积极的反馈',
    answer3Total: 'I',
    answer4: '我工作的努力得到别人的注意和认可',
    answer4Total: 'S',
  },
  {
    question: '有时,人们告诉我,我不应总是',
    answer1: '对任何事情报以怀疑',
    answer1Total: 'C',
    answer2: '过分要求',
    answer2Total: 'D',
    answer3: '以自己的方式行事',
    answer3Total: 'I',
    answer4: '遵循原则而不注意细节',
    answer4Total: 'S',
  },
  {
    //10
    question: '总的来讲,我喜欢我的上司是这样的:',
    answer1: '给我尽量可能多的自由和灵活性',
    answer1Total: 'I',
    answer2: '给我尽可能清晰,具体的工作指导',
    answer2Total: 'S',
    answer3: '给我尽可能多的知识和信息事',
    answer3Total: 'C',
    answer4: '给我尽可能多的权力',
    answer4Total: 'D',
  },
  {
    question: '在工作上我最大的担心是:',
    answer1: '不能完成目标',
    answer1Total: 'D',
    answer2: '做错事并受到批评',
    answer2Total: 'I',
    answer3: '被拒绝或对自己没有足够的了解',
    answer3Total: 'C',
    answer4: '突发性的事件令人感到没有安全感',
    answer4Total: 'S',
  },
  {
    //12
    question: '当我与这样一些人谈话时,有时会令我失去耐心,并被激怒',
    answer1: '对所发生的原因在解释时很肤浅,没有逻辑性',
    answer1Total: 'C',
    answer2: '对方抓不住重点',
    answer2Total: 'D',
    answer3: '让人觉得很无聊,没有意义',
    answer3Total: 'I',
    answer4: '对方不聆听或不在意我所讲的',
    answer4Total: 'S',
  },
  {
    question: '当他人对我的观点提出挑战时,我',
    answer1: '对所发生的原因在解释时很肤浅,没有逻辑性',
    answer1Total: 'S',
    answer2: '喜欢迎接挑战,并投入争论,尽力赢得胜利',
    answer2Total: 'D',
    answer3: '试图平静的证明我是正确的,他人是错误的',
    answer3Total: 'C',
    answer4: '在争论中,投入激情,但是相信我有能力说服他人,也容许被他人说服',
    answer4Total: 'I',
  },
  {
    question: '当我的工作任务太重的时候,我会:',
    answer1: '尽可能授权,既然我有能力说服别人帮助我做事',
    answer1Total: 'I',
    answer2: '通过告诉别人他们应该为我做什么尽可能的授权',
    answer2Total: 'D',
    answer3: '加倍的工作,尽量避免授权,因为很多重要的细节可能会被人们忽略',
    answer3Total: 'S',
    answer4: '尽量将自己的工作组织和计划一下,只是将工作授权给我真正相信的人',
    answer4Total: 'C',
  },
  {
    //15
    question: '在如下哪种环境中,我感觉到压力很大',
    answer1: '我有很多工作要做,而且不得不完全改变工作计划',
    answer1Total: 'S',
    answer2: '我有很多工作要做,并担心会影响我工作的质量',
    answer2Total: 'C',
    answer3:
      '我的工作微不足道,我及我的工作看起来对我的老板,公司毫无重要性可言。',
    answer3Total: 'D',
    answer4: '我几乎无事可做,没有任何进步',
    answer4Total: 'I',
  },
  {
    question: '当我不同意他人时,我会:',
    answer1: '平静和有条理的和他人论述',
    answer1Total: 'C',
    answer2: '挑战他人的观点并试图改变他的思想',
    answer2Total: 'D',
    answer3: '仔细聆听他人的争论,但尽力避免争论引起冲突',
    answer3Total: 'S',
    answer4: '推销自己的观点,通过运用自己的魅力, 热情和激情来赢得别人',
    answer4Total: 'I',
  },
  {
    question: '如果其他人让你失望,我通常会:',
    answer1:
      '即使在内心中我感到很受伤害,通常不会表现出来,而是进行小小的暗示表示自己的不满',
    answer1Total: 'S',
    answer2: '坦率表达我的气愤和失望',
    answer2Total: 'I',
    answer3: '我并不吃惊——我通常不相信别人会为我做什么',
    answer3Total: 'D',
    answer4: '安静避免冲突,但永远都不会忘记别人曾经不公平的对待我',
    answer4Total: 'C',
  },
  {
    question: '当一切都跟我过不去,我试图:',
    answer1: '坚持最主要的目标,先集中完成最基本,重要的部分',
    answer1Total: 'D',
    answer2: '成为“停顿”并且会经常征求他人的意见',
    answer2Total: 'S',
    answer3: '拿纸,笔坐下来系统,有条理分析哪里出了错,为什么',
    answer3Total: 'C',
    answer4: '尽量看到事情积极的一面,并始终乐观相信问题会解决的。',
    answer4Total: 'I',
  },
  {
    question: '我会对自己非常失望,当我:',
    answer1: '忽略了一些相关的事实,没有认真分析重要的信息',
    answer1Total: 'C',
    answer2: '给他人带来不好的影响或让他人失望',
    answer2Total: 'S',
    answer3: '错过一个新的,激动人心的机会,并发现为时已晚',
    answer3Total: 'I',
    answer4: '没有完成与我个人目标相关的任务',
    answer4Total: 'D',
  },
  {
    question: '如果将我放在一个不得不进行选择的情况下,我会选择:',
    answer1: '权力而不是赢得大众的欢迎',
    answer1Total: 'D',
    answer2: '注重隐私而不是曝光',
    answer2Total: 'C',
    answer3: '赢得大众的欢迎而不是权威',
    answer3Total: 'I',
    answer4: '安全而不是挑战务',
    answer4Total: 'S',
  },
];

export default QUESTIONS;
